"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv(override=True)

# AWS Configuration
AWS_CONFIG = {
    'region': os.getenv('AWS_S3_REGION'),
    'access_key': os.getenv('AWS_ACCESS_KEY_ID'),
    'secret_key': os.getenv('AWS_SECRET_ACCESS_KEY'),
    # Vide = AWS ; sinon endpoint S3-compatible (ex. https://s3.fr-par.scw.cloud)
    'endpoint_url': os.getenv('AWS_S3_ENDPOINT_URL'),
}

S3_PATHS = {
    'puissance': os.getenv('S3_PATH_PUISSANCE'),
    'annuel': os.getenv('S3_PATH_ANNUEL'),
    'mensuel': os.getenv('S3_PATH_MENSUEL'),
    'production': os.getenv('S3_PATH_PRODUCTION'),
    'production_annuel': os.getenv('S3_PATH_PRODUCTION_ANNUEL'),
    'production_mensuel': os.getenv('S3_PATH_PRODUCTION_MENSUEL'),
    'echanges': os.getenv('S3_PATH_ECHANGES'),
    'rte_eolien_production': os.getenv('S3_PATH_RTE_EOLIEN_PRODUCTION'),
    'rte_eolien_facteur_charge': os.getenv('S3_PATH_RTE_EOLIEN_FACTEUR_CHARGE'),
    'rte_solaire_production': os.getenv('S3_PATH_RTE_SOLAIRE_PRODUCTION'),
    'rte_solaire_facteur_charge': os.getenv('S3_PATH_RTE_SOLAIRE_FACTEUR_CHARGE'),
    'rte_pmax': os.getenv('S3_PATH_RTE_PMAX'),
}

# Local Parquet cache (see consommation/data_cache.py)
# Directory where Parquet files are downloaded from S3.  /tmp is ephemeral in
# prod (cleared on each deploy), which is intentional — clean slate on boot.
PARQUET_CACHE_DIR = os.getenv('PARQUET_CACHE_DIR', '/tmp/parquet_cache')
# How often (seconds) to re-check S3 ETags for freshness.  Default: 10 minutes.
# User-path safety net only: the background refresh thread (apps.py) normally
# keeps the cache warm, so requests never pay this check themselves.
PARQUET_CACHE_CHECK_TTL = int(os.getenv('PARQUET_CACHE_CHECK_TTL', '600'))
# Interval (seconds) of the background refresh thread.  0 disables the loop
# (one-shot warm-up at startup only, refresh falls back to the TTL above).
PARQUET_CACHE_REFRESH_INTERVAL = int(os.getenv('PARQUET_CACHE_REFRESH_INTERVAL', '600'))

# OIDC Configuration (provider-agnostic via OpenID Connect discovery).
# OIDC_ISSUER is the base URL of the IdP, e.g. https://<instance>.zitadel.cloud
OIDC_ISSUER = os.getenv('OIDC_ISSUER', '')
OIDC_CLIENT_ID = os.getenv('OIDC_CLIENT_ID', '')
OIDC_CLIENT_SECRET = os.getenv('OIDC_CLIENT_SECRET', '')
OIDC_SCOPES = os.getenv('OIDC_SCOPES', 'openid profile email')
# Langue forcée de l'UI de login de l'IdP (ui_locales). Vide = langue du navigateur.
OIDC_UI_LOCALES = os.getenv('OIDC_UI_LOCALES', 'fr')
# PAT d'un service user Zitadel (rôle Org User Manager) — permet la fermeture de
# compte in-app (suppression de l'utilisateur chez l'IdP, cf. idp_admin.py).
# Vide = fonctionnalité masquée. ⚠️ Zitadel-spécifique, et le PAT expire.
ZITADEL_SERVICE_TOKEN = os.getenv('ZITADEL_SERVICE_TOKEN', '')

# Chatbot (Mistral API)
MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY', '')
CHAT_MODEL = os.getenv('CHAT_MODEL', 'mistral-medium-latest')
CHAT_MAX_TURNS = int(os.getenv('CHAT_MAX_TURNS', '30'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    # Dev: default key is acceptable for local development
    SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-only-not-for-production')
else:
    # Prod: SECRET_KEY is mandatory, crash if missing
    SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")
]

# Dev local : l'app est souvent atteinte via le port-forwarding (localhost:8000,
# y compris derrière le proxy TLS d'un Codespace → Origin https://localhost:8000).
# Django vérifie l'en-tête Origin sur les POST : sans ces entrées, les
# formulaires sont rejetés en 403 CSRF. Limité à DEBUG, sans effet en prod.
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000", "https://localhost:8000",
        "http://127.0.0.1:8000", "https://127.0.0.1:8000",
    ]

# GitHub Codespaces: the app is reached via a forwarded *.app.github.dev URL
# behind a TLS-terminating proxy.  Trust that host and its X-Forwarded-Proto so
# request.build_absolute_uri() yields https — required for the OIDC callback.
# Only active inside a Codespace; no effect on local dev or prod.
_codespace_name = os.getenv('CODESPACE_NAME')
if _codespace_name:
    _fwd_domain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN', 'app.github.dev')
    _codespace_host = f"{_codespace_name}-8000.{_fwd_domain}"
    ALLOWED_HOSTS.append(_codespace_host)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_codespace_host}")
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # The proxy forwards with Host: localhost:8000 and puts the real public
    # host in X-Forwarded-Host — use the latter so redirect_uri is correct.
    USE_X_FORWARDED_HOST = True

# Security settings for production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Nombre de proxys de confiance devant l'app (Clever Cloud : nginx local = 1,
# à revérifier si le throttling voit des IPs anormales). Indique à Django
# Ninja de prendre la dernière IP de X-Forwarded-For (celle ajoutée par le
# proxy = client réel) pour identifier les clients du throttling, au lieu de
# concaténer tout l'en-tête — qui est falsifiable et permettrait de contourner
# la limite de débit. En local (pas de proxy, pas de XFF), REMOTE_ADDR est
# utilisé : aucun impact.
NINJA_NUM_PROXIES = int(os.getenv('NINJA_NUM_PROXIES', '1'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'consommation', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'consommation.context_processors.oidc_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Les données de visualisation viennent de S3 (DuckDB), PAS d'une base. La base
# ne sert qu'à un usage léger : stocker les clés d'API générées par les
# utilisateurs (cf. consommation/models.py).
# - En prod : `DATABASE_URL` pointe vers la Postgres (add-on Clever Cloud/…).
# - En local sans `DATABASE_URL` : fallback SQLite (fichier db.sqlite3) pour
#   pouvoir tester sans dépendre d'une base distante.
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Session configuration - use signed cookies (no database required)
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# La session porte à la fois l'état de connexion OIDC et la mémoire des filtres
# des graphiques (dates_conso, dates_production, dates_echanges…). On la limite
# à 1 h : passé ce délai depuis la dernière écriture de session (login ou
# soumission d'un filtre), l'utilisateur est déconnecté et les filtres
# reviennent à leurs valeurs par défaut.
SESSION_COOKIE_AGE = 3600
# Mode glissant : chaque requête réécrit la session, ce qui repousse
# l'expiration d'1 h. La déconnexion / reset des filtres intervient donc après
# 1 h d'inactivité réelle, pas 1 h après la connexion.
SESSION_SAVE_EVERY_REQUEST = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME') or None
if FORCE_SCRIPT_NAME:
    STATIC_URL = FORCE_SCRIPT_NAME.rstrip('/') + '/static/'
else:
    STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
} 
